### ISSUE TITLE
newer unfortunatly unrelated repository tree at GitHub

### ISSUE THREAD

**Issue by pbiering** [vdr-projects/vdradmin-am#1]
Please check unfortunatly not forked https://github.com/glenvt18/vdradmin-am and its (currently open) pull requests, potentially it would be a good idea to merge somehow back to the original master.

**Comment by M-Reimer** [comment]
I'm pretty sure the repository in context of vdr-projects was created in the process of backing up everything that existed on projects.vdr-developer.org before it got shut down. So the repository you mentioned existed before the backup repo here was created and was initially forked from projects.vdr-developer.org.

The open pull requests were just created few days ago, so I don't see a reason why it wouldn't be an option to just wait a little longer. If they do get picked up, I would mark the repository here as public archive linking to his repo as the "currently active developed repo".

Even if the pull requests are not merged for a longer period of time, getting a few of them accepted on a repo in context of vdr-projects would require someone to formally accept being the maintainer of the project as "community maintenance" is not about adding major changes but to keep something usable. It wouldn't do any good if everything pointed as a pull request to a vdr-projects repo is just merged without any checking done before.

Edit: Had a look at all pull requests and I guess most of them could be merged after getting a bit more info about some changes. But in general major changes will be kept as open pull requests until a few people verify that they tested the change and it works for them. The only alternative would be someone accepting to (co-)maintain the repo and merging himself. If it causes issues later on, it would be his job to hopefully provide a fix in time.

**Comment by pbiering** [comment]
> Edit: Had a look at all pull requests and I guess most of them could be merged after getting a bit more info about some changes. But in general major changes will be kept as open pull requests until a few people verify that they tested the change and it works for them. The only alternative would be someone accepting to (co-)maintain the repo and merging himself. If it causes issues later on, it would be his job to hopefully provide a fix in time.

@scop / @glenvt18: what is the status of https://github.com/glenvt18/vdradmin-am ? stale or active?

As I'm already co-maintainer of https://github.com/vdr-projects/vdr-plugin-osdteletext it would be no problem if at least I can also be upgraded to co-maintainer of https://github.com/vdr-projects/vdradmin-am if the current 3 ones are too busy. Potentially even @MegaV0lt  would be a candidate for being a co-maintainer.

Redirecting the current open PRs into a new development branch in the master repo should be not a big issue btw. and finally all is "back" on the expected master repo and community has not search for and compare all the forks...

**Comment by scop** [comment]
No idea. I haven't been involved with these projects in a long time, nor do I think I have any maintainer access.

**Comment by MegaV0lt** [comment]
Thanks for the offer, but my programing knowledge is very limited. I don't think i can be a maintainer here

Edit: I wrote a mail to the original author. Maybe we get an answer from @a-mair.

**Comment by a-mair** [comment]
> As I'm already co-maintainer of https://github.com/vdr-projects/vdr-plugin-osdteletext it would be no problem if at least I can also be upgraded to co-maintainer of https://github.com/vdr-projects/vdradmin-am if the current 3 ones are too busy.

I don't mind if you are upgraded to co-maintainer, but I must say that I've little time to be active here soon.

I've plans to commit and maintain my other projects here, too. There are some code changes not yet published, but time to review and publish is little. So is motivation at the moment. Sorry. But I'm not out.

**Comment by M-Reimer** [comment]
Having the original developer here changes everything.
I've created and merged a pull request myself which merges back all changes done in the repo at https://github.com/glenvt18/vdradmin-am
Invitations for the "Maintainer" role are out to @a-mair and @pbiering 
I'll close here, now. I think all the remaining stuff can be managed by @pbiering
Project is also listed at https://vdr-projects.github.io/ with a note that there is an active maintainer.

@a-mair Can you please open a new issue here: https://github.com/vdr-projects/vdr-projects.github.io/issues and list your other projects so I can give you maintainer access?

**Comment by pbiering** [comment]
Thank you for extending my role. Have now "re-based" the open pull requests.

**Comment by pbiering** [comment]
@a-mair : can you please adjust the broken "GIT access" URL on your page: http://andreas.vdr-developer.org/vdradmin-am/download.html ?

One can also think about making future releases available here: https://github.com/vdr-projects/vdradmin-am/releases

**Comment by a-mair** [comment]
Sure, adjusted.

**Comment by M-Reimer** [comment]
As quite a few new pull requests now have arrived here: I'll unfollow this project now. I can't contribute to every project that landed on vdr-projects and I don't have vdradmin-am installed nor do I plan to do so. I hope @pbiering can handle the pending pull requests.

**Comment by pbiering** [comment]
release 3.6.11 created (still in pre-release stage), feel free to test: https://github.com/vdr-projects/vdradmin-am/releases
