### ISSUE TITLE
Crash with umlauts (äöü)

### ISSUE THREAD

**Issue by MegaV0lt** [vdr-projects/vdradmin-am#18]
VDRAmin crashes when a search has german umlauts. See here: https://www.vdr-portal.de/forum/index.php?thread/134724-0-7-vdradmin-update/&postID=1359138#post1359138

Possible solution:
https://www.vdr-portal.de/forum/index.php?thread/134724-0-7-vdradmin-update/&postID=1359146#post1359146

**Comment by FireFlyVDR** [comment]
Here also as patch, it should change line 6010 in your version
[vdradmin-am-3.6.10-fix_umlaut_search.patch.txt](https://github.com/vdr-projects/vdradmin-am/files/11626107/vdradmin-am-3.6.10-fix_umlaut_search.patch.txt)

**Comment by pbiering** [comment]
confirmed, fixed, thank you for the patch
