### ISSUE TITLE
Display EPG images with filename including channel ID

### ISSUE THREAD

**Issue by FireFlyVDR** [vdr-projects/vdradmin-am#19]
Patch for displaying EPG images of the form <channelID>_<EPG_ID>\*.jpg
Currently only <EPG_ID>\*.jpg is used which could lead to wrong pictures when more than one channel use the same EPG_ID.
It also increases the width of the EPG window from 500 to 550 px to avoid horizontal scrollbars.
[vdradmin-am-3.6.10-epgimage-fullname.diff.txt](https://github.com/vdr-projects/vdradmin-am/files/11626179/vdradmin-am-3.6.10-epgimage-fullname.diff.txt)

**Comment by pbiering** [comment]
thank you for the patch, please test latest "master"

**Comment by FireFlyVDR** [comment]
Thanks, it works as suggested.
I think it would make sense to enlarge the EPG window further to see the first image (at least partly). Currently the images are "hidden" below the text and can only be seen when scrolling down. 
As the default values for GUI_POPUP_HEIGHT and GUI_POPUP_HEIGHT are overwritten by those from the config file these would take effect only for new setups or if the two are deleted from the conf file.
[vdradmin-enlarge_epg_window.diff.txt](https://github.com/vdr-projects/vdradmin-am/files/11635444/vdradmin-enlarge_epg_window.diff.txt)

**Comment by pbiering** [comment]
patch committed, check again latest "master"

**Comment by FireFlyVDR** [comment]
Looks like it's not yet in the master, but as the patch consists only of changing two numbers I think an additional check is not necessary.

**Comment by pbiering** [comment]
sorry, did push the patch to merged branch by accident, please try now "master"

**Comment by FireFlyVDR** [comment]
Now it works as expected.

**Comment by pbiering** [comment]
thank you for confirmation, v3.6.13 released now
